version: '3.8'

services:
  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus_hb
    ports:
      - "9090:9090"   # Exposes Prometheus on port 9090
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml  # Prometheus config file
    networks:
      - monitoring
    restart: unless-stopped

  grafana:
    image: grafana/grafana:latest
    container_name: grafana_hb
    ports:
      - "3001:3001"   # Exposes Grafana on port 3001
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin  # Set Grafana admin password
    depends_on:
      - prometheus_hb
    networks:
      - monitoring
    restart: unless-stopped

networks:
  monitoring:
    driver: bridge
