global:
  scrape_interval: 15s  # How often to scrape targets by default

scrape_configs:
  - job_name: 'django_app'
    static_configs:
      - targets: ['docker.for.mac.localhost:8000']
  
  - job_name: 'next_app'
    static_configs:
      - targets: ['docker.for.mac.localhost:3000']

remote_write:
- url: http://localhost:3000/
  basic_auth:
    username: admin
    password: admin
